config = dict(
    env_id="PandaHandoverBimanual-v1",
    num_workers=64,
    log_dir="logs/handover/attention_discrete/1b_os0.5_inhand0.5_dense_newobjinhand",
    total_timesteps=int(1e8),
    create_env_kwargs=dict(
        obs_keys=["observation", "achieved_goal", "desired_goal"],
        done_when_success=False,
        reward_scale=10,
        kwargs=dict(
            os_rate=0.5,
            obj_in_hand_rate=0.5,
            reward_type="dense",
        ),
    ),
    policy_type="attention_discrete",
    obs_parser=dict(
        robot_dim=14,
        obj_dim=18,
        goal_dim=3,
    ),
    policy=dict(
        hidden_size=64,
        num_bin=21,
        feature_extractor="self_attention",
        shared=False,
        n_critic_layers=1,
        n_actor_layers=1,
        kwargs=dict(
            n_attention_blocks=3,
            n_heads=1,
        ),
    ),
)